# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\coding\python\MyCloud\qt\UI\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1292, 934)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 20, 1181, 51))
        self.widget.setObjectName("widget")
        self.minButton = QtWidgets.QPushButton(self.widget)
        self.minButton.setGeometry(QtCore.QRect(1090, 10, 41, 41))
        self.minButton.setText("")
        self.minButton.setObjectName("minButton")
        self.closeButton = QtWidgets.QPushButton(self.widget)
        self.closeButton.setGeometry(QtCore.QRect(1130, 10, 41, 41))
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.name = QtWidgets.QLabel(self.widget)
        self.name.setGeometry(QtCore.QRect(90, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.logo = QtWidgets.QLabel(self.widget)
        self.logo.setGeometry(QtCore.QRect(30, 4, 51, 41))
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.user_btn = QtWidgets.QPushButton(self.widget)
        self.user_btn.setGeometry(QtCore.QRect(970, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.user_btn.setFont(font)
        self.user_btn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.user_btn.setObjectName("user_btn")
        self.user_icon = QtWidgets.QLabel(self.widget)
        self.user_icon.setGeometry(QtCore.QRect(930, 10, 31, 31))
        self.user_icon.setText("")
        self.user_icon.setObjectName("user_icon")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(50, 70, 211, 661))
        self.widget_2.setObjectName("widget_2")
        self.allfile_btn = QtWidgets.QPushButton(self.widget_2)
        self.allfile_btn.setGeometry(QtCore.QRect(0, 0, 211, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        self.allfile_btn.setFont(font)
        self.allfile_btn.setObjectName("allfile_btn")
        self.doc_btn = QtWidgets.QPushButton(self.widget_2)
        self.doc_btn.setGeometry(QtCore.QRect(0, 40, 211, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        self.doc_btn.setFont(font)
        self.doc_btn.setObjectName("doc_btn")
        self.img_btn = QtWidgets.QPushButton(self.widget_2)
        self.img_btn.setGeometry(QtCore.QRect(0, 80, 211, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        self.img_btn.setFont(font)
        self.img_btn.setObjectName("img_btn")
        self.music_btn = QtWidgets.QPushButton(self.widget_2)
        self.music_btn.setGeometry(QtCore.QRect(0, 120, 211, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        self.music_btn.setFont(font)
        self.music_btn.setObjectName("music_btn")
        self.video_btn = QtWidgets.QPushButton(self.widget_2)
        self.video_btn.setGeometry(QtCore.QRect(0, 160, 211, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        self.video_btn.setFont(font)
        self.video_btn.setObjectName("video_btn")
        self.other_btn = QtWidgets.QPushButton(self.widget_2)
        self.other_btn.setGeometry(QtCore.QRect(0, 200, 211, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        self.other_btn.setFont(font)
        self.other_btn.setObjectName("other_btn")
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setGeometry(QtCore.QRect(40, 240, 211, 611))
        self.widget_6.setObjectName("widget_6")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(260, 70, 971, 661))
        self.widget_3.setObjectName("widget_3")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_3)
        self.tableWidget.setGeometry(QtCore.QRect(20, 70, 931, 571))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(20, 10, 931, 51))
        self.widget_4.setObjectName("widget_4")
        self.back_btn = QtWidgets.QPushButton(self.widget_4)
        self.back_btn.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.back_btn.setText("")
        self.back_btn.setObjectName("back_btn")
        self.forward_btn = QtWidgets.QPushButton(self.widget_4)
        self.forward_btn.setGeometry(QtCore.QRect(50, 10, 31, 31))
        self.forward_btn.setText("")
        self.forward_btn.setObjectName("forward_btn")
        self.refresh_btn = QtWidgets.QPushButton(self.widget_4)
        self.refresh_btn.setGeometry(QtCore.QRect(100, 10, 31, 31))
        self.refresh_btn.setText("")
        self.refresh_btn.setObjectName("refresh_btn")
        self.upload_btn = QtWidgets.QPushButton(self.widget_4)
        self.upload_btn.setGeometry(QtCore.QRect(190, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        self.upload_btn.setFont(font)
        self.upload_btn.setObjectName("upload_btn")
        self.mkdir_btn = QtWidgets.QPushButton(self.widget_4)
        self.mkdir_btn.setGeometry(QtCore.QRect(290, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        self.mkdir_btn.setFont(font)
        self.mkdir_btn.setObjectName("mkdir_btn")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit.setGeometry(QtCore.QRect(640, 10, 241, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.search_btn = QtWidgets.QPushButton(self.widget_4)
        self.search_btn.setGeometry(QtCore.QRect(890, 10, 31, 31))
        self.search_btn.setText("")
        self.search_btn.setObjectName("search_btn")
        self.transfer_btn = QtWidgets.QPushButton(self.widget_4)
        self.transfer_btn.setGeometry(QtCore.QRect(480, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.transfer_btn.setFont(font)
        self.transfer_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.transfer_btn.setObjectName("transfer_btn")
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(260, 70, 971, 661))
        self.widget_5.setObjectName("widget_5")
        self.widget.raise_()
        self.widget_2.raise_()
        self.widget_5.raise_()
        self.widget_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MyCloud"))
        self.name.setText(_translate("MainWindow", "iDrive"))
        self.user_btn.setText(_translate("MainWindow", "user"))
        self.allfile_btn.setText(_translate("MainWindow", "全部文件"))
        self.doc_btn.setText(_translate("MainWindow", "文档"))
        self.img_btn.setText(_translate("MainWindow", "图片"))
        self.music_btn.setText(_translate("MainWindow", "音乐"))
        self.video_btn.setText(_translate("MainWindow", "视频"))
        self.other_btn.setText(_translate("MainWindow", "其他"))
        self.upload_btn.setText(_translate("MainWindow", "上传"))
        self.mkdir_btn.setText(_translate("MainWindow", "新建文件夹"))
        self.transfer_btn.setText(_translate("MainWindow", "传输列表"))
